### ISSUE TITLE
mirc color code issue

### ISSUE THREAD

**Issue by net-bitsDotNet** [net-bits-net/nbwebchat_v4#2]
If you set the background color it repeats text twice. Reported by danger.

**Comment by err0r007** [comment]
unable to reproduce bug

**Comment by net-bitsDotNet** [comment]
I'll check with danger.

**Comment by net-bitsDotNet** [comment]
`:danger!8.64cbb5.aa713fa341f6786c39b587498449a999@SPCNMember PRIVMSG %#Test :char(03)0,2 char(03)0,7 [Game Info] char(03)0,2 "1wk 21 Hours 38 Minutes" To Gain "7,000,000" Points For 1st (Average Points For "" Games: 2,000|Total Game Time: 0 Seconds) `

^ raw code. Game Info is printed out twice after formatting.

**Comment by err0r007** [comment]
this issue is resolved.
