### ISSUE TITLE
OK NOTHING TO SEE HERE

### ISSUE THREAD

**Issue by danger2uXXX** [net-bits-net/nbwebchat_v4#6]
Me bitching, nothing to see here
_

**Comment by danger2uXXX** [comment]
> Death To SPCN Is The Game, No Bad Feelings Towards You SC or err0r but im going to make that batty f****r Jeffs chat life a bitch and kill SPCN is the Goal but losing it google ads is the start, Every clicked an Ad Vendor 50,000 times, well i have on 6 of them lets see how long your Google support last now
> 
> _

its on bitches

**Comment by Tactical-Thunder** [comment]
Being as None of the Staff owns SPCN, and I can walk away at anytime, I don't have a clue what you are trying to accomplish, except to feed your ego.

**Comment by danger2uXXX** [comment]
> Being as None of the Staff owns SPCN, and I can walk away at anytime, I don't have a clue what you are trying to accomplish, except to feed your ego.

TT it was not you if im 100% honest, ive been on my last straw with existence since yesterday morning mountain just tipped me off the edge, I dont enjoy trying to kill chat servers but its abit late my click bot is on 100k clicks for 8 google ads off SPCN, as for the room flooding you know how i get when i get banned or threatened i just strike out without concern for myself or loved ones, im the same in RL i burn them down or smash them up without a thought to myself or anyone else, guess im just crazy or if not a im a couple or mars bars past a multipack anyways Eclissi has convinced me to allow her to keep her room in peace without me turning it all into a war zone so i give up, you win, have a good life

**Comment by Tactical-Thunder** [comment]
There are no winners here. Take that statement for what it's worth, and I sincerely mean it.

**Comment by danger2uXXX** [comment]
There never is unless you playing trivia or word frenzy, Lotto is impossible, Bingo is possible but I'm too young, and my cars a piece of shit a 10 year old on a BMX could beat me in a race
